from playwright.sync_api import sync_playwright
U='file://../dist/index.html'
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={'width':520,'height':900})
    errs=[]; pg.on('console', lambda m: m.type=='error' and errs.append(m.text)); pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.add_init_script(path='mock.js')
    pg.goto(U+'#role-selection'); pg.wait_for_timeout(300)
    pg.click('text=ENTER PATIENT MODE'); pg.wait_for_timeout(200)
    print('screen', pg.evaluate("document.querySelector('.screen:not([hidden])').id"))
    pg.click('[data-add-slot="morning"]'); pg.wait_for_timeout(200)
    print('screen', pg.evaluate("document.querySelector('.screen:not([hidden])').id"), 'freq', pg.input_value('#f-freq'))
    pg.set_input_files('#ocr-file','/tmp/claude-0/rx.png'); pg.wait_for_timeout(600)
    print('fields', [pg.input_value(x) for x in ['#f-name','#f-dose','#f-freq','#f-days','#f-doc']], pg.inner_text('#ocr-status'))
    pg.click('#ocr-save'); pg.wait_for_timeout(500)
    print('screen', pg.evaluate("document.querySelector('.screen:not([hidden])').id"))
    print('meds', pg.evaluate("Object.entries(window.__store).filter(([k])=>k.startsWith('meds')).map(([k,v])=>v.slots)"))
    print('next', pg.inner_text('#pd-next-title'), '|', pg.inner_text('#pd-next-sub').replace('\n',' / '))
    print('slots', pg.evaluate("[...document.querySelectorAll('[data-slot-list]')].map(e=>e.textContent)"))
    pg.evaluate("window.__showScreen('medication-reminder')"); pg.wait_for_timeout(200)
    print('mr', pg.inner_text('#mr-name'), '|', pg.inner_text('#mr-time'))
    pg.click('#mr-taken'); pg.wait_for_timeout(400)
    print('screen', pg.evaluate("document.querySelector('.screen:not([hidden])').id"), pg.inner_text('#da-last'))
    pg.evaluate("window.__showScreen('caretaker-dashboard')"); pg.wait_for_timeout(200)
    print('ct', [pg.inner_text(x).replace('\n',' ') for x in ['#ct-adh','#ct-taken','#ct-snoozed','#ct-missed','#ct-pending','#ct-feed-title']])
    pg.screenshot(path='/tmp/claude-0/flow-ct.png', full_page=True)
    print('errors', errs)
    b.close()
